### ISSUE TITLE
Are URL templates of `git.typo3.org` still up-to-date?

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/sphinxcontrib-gitloginfo#1]
There have been changes in the `git.typo3.org` instance recently, and, for example, `git://git.typo3.org/Packages/TYPO3` has been replaced with `https://github.com/TYPO3/typo3` officially for downloading TYPO3 CMS. Do the URLs in this repository still apply for the current GitLab instance running at `git.typo3.org`?

**Comment by marble** [comment]
This repo comes to action only AFTER the project it is working on has been cloned by some other preparation step. So it is not affected by where the original repo is kept. In other words: This repo doesn't care about HOW Bamboo or GitHub Actions or some other script fetches the data - it starts working once the copy is made. So nothing to do here. The README happens to just use `TYPO3.CMS.git` as a speaking example name.
